/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData coffee = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData github_circled =
      IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam);
  static const IconData medium = IconData(0xf23a, fontFamily: _kFontFam);
  static const IconData twitter_squared =
      IconData(0xf304, fontFamily: _kFontFam);
}
